// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgcWXk0qHqgVmU1sAPfC2soSrzaqz3e1c',
    appId: '1:220851171253:web:34241edc9c36d9a17533fc',
    messagingSenderId: '220851171253',
    projectId: 'tech-zone-1ae2e',
    authDomain: 'tech-zone-1ae2e.firebaseapp.com',
    storageBucket: 'tech-zone-1ae2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_fIwnwW8UriRGDsC2Q35G97ramuf7uFI',
    appId: '1:220851171253:android:11777909b4489a877533fc',
    messagingSenderId: '220851171253',
    projectId: 'tech-zone-1ae2e',
    storageBucket: 'tech-zone-1ae2e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgcWXk0qHqgVmU1sAPfC2soSrzaqz3e1c',
    appId: '1:220851171253:web:7f5802bb977fb0307533fc',
    messagingSenderId: '220851171253',
    projectId: 'tech-zone-1ae2e',
    authDomain: 'tech-zone-1ae2e.firebaseapp.com',
    storageBucket: 'tech-zone-1ae2e.firebasestorage.app',
  );
}
